name = input("Enter Name: ")
college = input("Enter College Name: ")
branch = input("Enter Branch: ")
gender = input("Enter gender: ")
age = int(input("Enter Age: "))
print(name)
print(college)
print(branch)
print(gender)
print(age)
